const defaultBooks = [
	{
		title: "Thinking, Fast and Slow",
		author: "Daniel Kahneman",
		genre: "Tâm lý học",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/top/sach1.jpg",
	},
	{
		title: "Influence",
		author: "Robert B. Cialdini",
		genre: "Tâm lý học",
		year: "1984",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/top/sach2.jpg",
	},
	{
		title: "The Power of Habit",
		author: "Charles Duhigg",
		genre: "Tâm lý học",
		year: "2012",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/top/sach3.jpg",
	},
	{
		title: "Emotional Intelligence",
		author: "Daniel Goleman",
		genre: "Tâm lý học",
		year: "1995",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/top/sach4.jpg",
	},
	{
		title: "The Psychology of Money",
		author: "Morgan Housel",
		genre: "Tâm lý học",
		year: "2020",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/top/sach5.jpg",
	},
	{
		title: "Thao túng tâm lý",
		author: "Robin Dreeke",
		genre: "Tâm lý học",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/yeuthich/sach1.jpg",
	},
	{
		title: "Man’s Search for Meaning",
		author: "Viktor E. Frankl",
		genre: "Tâm lý học",
		year: "1946",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach1.jpg",
	},
	{
		title: "Flow",
		author: "Mihaly Csikszentmihalyi",
		genre: "Tâm lý học",
		year: "1990",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach2.jpg",
	},
	{
		title: "Games People Play",
		author: "Eric Berne",
		genre: "Tâm lý học",
		year: "1964",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach3.jpg",
	},
	{
		title: "The Art of Thinking Clearly",
		author: "Rolf Dobelli",
		genre: "Tâm lý học",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach4.jpg",
	},
	{
		title: "Đắc Nhân Tâm",
		author: "Dale Carnegie",
		genre: "Tâm lý học",
		year: "1936",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach5.jpg",
	},
	{
		title: "How Psychology Works",
		author: "DK",
		genre: "Tâm lý học",
		year: "2018",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach6.jpg",
	},
	{
		title: "Sức mạnh của hiện tại",
		author: "Eckhart Tolle",
		genre: "Tâm lý học",
		year: "1997",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach7.jpg",
	},
	{
		title: "Đọc vị bất kỳ ai",
		author: "David J. Lieberman",
		genre: "Tâm lý học",
		year: "2006",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach8.jpg",
	},
	{
		title: "Bạn không thông minh lắm đâu",
		author: "David McRaney",
		genre: "Tâm lý học",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/tamlyhoc/thuong/sach9.jpg",
	},
	{
		title: "Don Quixote",
		author: "Miguel de Cervantes",
		genre: "Tiểu thuyết các loại",
		year: "1605",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/top/sach1.jpg",
	},
	{
		title: "A Tale Of Two Cities",
		author: "Charles Dickens",
		genre: "Tiểu thuyết các loại",
		year: "1859",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/top/sach2.jpg",
	},
	{
		title: "One Hundred Years of Solitude",
		author: "Gabriel Garcia Marquez",
		genre: "Tiểu thuyết các loại",
		year: "1967",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/top/sach3.jpg",
	},
	{
		title: "The Catcher in the Rye",
		author: "J.D. Salinger",
		genre: "Tiểu thuyết các loại",
		year: "1951",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/top/sach4.jpg",
	},
	{
		title: "To Kill a Mockingbird",
		author: "Harper Lee",
		genre: "Tiểu thuyết các loại",
		year: "1960",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/top/sach5.jpg",
	},
	{
		title: "Nanh Trắng",
		author: "Jack London",
		genre: "Tiểu thuyết các loại",
		year: "1906",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/yeuthich/sach1.jpg",
	},
	{
		title: "Tiếng gọi nơi hoang dã",
		author: "Jack London",
		genre: "Tiểu thuyết các loại",
		year: "1903",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/yeuthich/sach2.jpg",
	},
	{
		title: "Crime and Punishment",
		author: "Fyodor Dostoevsky",
		genre: "Tiểu thuyết các loại",
		year: "1866",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach1.jpg",
	},
	{
		title: "The Great Gatsby",
		author: "F. Scott Fitzgerald",
		genre: "Tiểu thuyết các loại",
		year: "1925",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach2.jpg",
	},
	{
		title: "Les Misérables",
		author: "Victor Hugo",
		genre: "Tiểu thuyết các loại",
		year: "1862",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach3.jpg",
	},
	{
		title: "Không gia đình",
		author: "Hector Malot",
		genre: "Tiểu thuyết các loại",
		year: "1878",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach4.jpg",
	},
	{
		title: "Miếng Da Lừa",
		author: "Honoré De Balzac",
		genre: "Tiểu thuyết các loại",
		year: "1831",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach5.jpg",
	},
	{
		title: "Bố già",
		author: "Mario Puzo",
		genre: "Tiểu thuyết các loại",
		year: "1969",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach6.jpg",
	},
	{
		title: "Số đỏ",
		author: "Vũ Trọng Phụng",
		genre: "Tiểu thuyết các loại",
		year: "1936",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach7.jpg",
	},
	{
		title: "Vụ án",
		author: "Franz Kafka",
		genre: "Tiểu thuyết các loại",
		year: "1925",
		quantity: 1000,
		image: "/anh/sach/tieuthuyet/thuong/sach8.jpg",
	},
	{
		title: "The Da Vinci Code",
		author: "Dan Brown",
		genre: "Trinh thám",
		year: "2003",
		quantity: 1000,
		image: "/anh/sach/trinhtham/top/sach1.jpg",
	},
	{
		title: "The Caves of Steel",
		author: "Isaac Asimov",
		genre: "Trinh thám",
		year: "1954",
		quantity: 1000,
		image: "/anh/sach/trinhtham/top/sach2.jpg",
	},
	{
		title: "Where the Crawdads Sing",
		author: "Delia Owens",
		genre: "Trinh thám",
		year: "2018",
		quantity: 1000,
		image: "/anh/sach/trinhtham/top/sach3.jpg",
	},
	{
		title: "All the Light We Cannot See",
		author: "Anthony Doerr",
		genre: "Trinh thám",
		year: "2014",
		quantity: 1000,
		image: "/anh/sach/trinhtham/top/sach4.jpg",
	},
	{
		title: "The Book Thief",
		author: "Markus Zusak",
		genre: "Trinh thám",
		year: "2005",
		quantity: 1000,
		image: "/anh/sach/trinhtham/top/sach5.jpg",
	},
	{
		title: "Hỏa Ngục",
		author: "Dan Brown",
		genre: "Trinh thám",
		year: "2013",
		quantity: 1000,
		image: "/anh/sach/trinhtham/yeuthich/sach1.jpg",
	},
	{
		title: "Murder on the Orient Express",
		author: "Agatha Christie",
		genre: "Trinh thám",
		year: "1934",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach1.jpg",
	},
	{
		title: "The Hound of the Baskervilles",
		author: "Arthur Conan Doyle",
		genre: "Trinh thám",
		year: "1902",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach2.jpg",
	},
	{
		title: "Big Little Lies",
		author: "Liane Moriarty",
		genre: "Trinh thám",
		year: "2014",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach3.jpg",
	},
	{
		title: "In the Woods",
		author: "Tana French",
		genre: "Trinh thám",
		year: "2007",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach4.jpg",
	},
	{
		title: "Sherlock Holmes",
		author: "Arthur Conan Doyle",
		genre: "Trinh thám",
		year: "1892",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach5.jpg",
	},
	{
		title: "Kỳ án ánh trăng",
		author: "Quỷ Cổ Nữ",
		genre: "Trinh thám",
		year: "2005",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach6.jpg",
	},
	{
		title: "Phía sau Nghi can X",
		author: "Higashino Keigo",
		genre: "Trinh thám",
		year: "2005",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach7.jpg",
	},
	{
		title: "Cô gái có hình xăm rồng",
		author: "Stieg Larsson",
		genre: "Trinh thám",
		year: "2005",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach8.jpg",
	},
	{
		title: "Vòng tròn máu",
		author: "Edgar Wallace",
		genre: "Trinh thám",
		year: "2019",
		quantity: 1000,
		image: "/anh/sach/trinhtham/thuong/sach9.jpg",
	},
	{
		title: "Fifty Shades of Grey",
		author: "E. L. James",
		genre: "Ngôn tình",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/ngontinh/top/sach1.jpg",
	},
	{
		title: "Pride and Prejudice",
		author: "Jane Austen",
		genre: "Ngôn tình",
		year: "1813",
		quantity: 1000,
		image: "/anh/sach/ngontinh/top/sach2.jpg",
	},
	{
		title: "The Notebook",
		author: "Nicholas Sparks",
		genre: "Ngôn tình",
		year: "1996",
		quantity: 1000,
		image: "/anh/sach/ngontinh/top/sach3.jpg",
	},
	{
		title: "Outlander",
		author: "Diana Gabaldon",
		genre: "Ngôn tình",
		year: "1991",
		quantity: 1000,
		image: "/anh/sach/ngontinh/top/sach4.jpg",
	},
	{
		title: "Me Before You",
		author: "Jojo Moyes",
		genre: "Ngôn tình",
		year: "2012",
		quantity: 1000,
		image: "/anh/sach/ngontinh/top/sach5.jpg",
	},
	{
		title: "Hồ Điệp Kình Ngư",
		author: "Tuế Kiến",
		genre: "Ngôn tình",
		year: "2024",
		quantity: 1000,
		image: "/anh/sach/ngontinh/yeuthich/sach1.jpg",
	},
	{
		title: "Twilight",
		author: "Stephenie Meyer",
		genre: "Ngôn tình",
		year: "2005",
		quantity: 1000,
		image: "/anh/sach/ngontinh/most/sach1.jpg",
	},
	{
		title: "Beautiful Disaster",
		author: "Jamie McGuire",
		genre: "Ngôn tình",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach1.jpg",
	},
	{
		title: "Eleanor & Park",
		author: "Rainbow Rowell",
		genre: "Ngôn tình",
		year: "2013",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach2.jpg",
	},
	{
		title: "It Ends with Us",
		author: "Colleen Hoover",
		genre: "Ngôn tình",
		year: "2016",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach3.jpg",
	},
	{
		title: " Boss là nữ phụ",
		author: "Mặc Linh",
		genre: "Ngôn tình",
		year: "2019",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach4.jpg",
	},
	{
		title: "Chọc tức vợ yêu",
		author: "Quẫn Quẫn Hữu Yêu",
		genre: "Ngôn tình",
		year: "2017",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach5.jpg",
	},
	{
		title: "Mãi mãi là bao xa",
		author: "Diệp Lạc Vô Tâm",
		genre: "Ngôn tình",
		year: "2013",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach6.jpg",
	},
	{
		title: "All in love",
		author: "Cố Tây Tước",
		genre: "Ngôn tình",
		year: "2020",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach7.jpg",
	},
	{
		title: "Hồ ly biết yêu",
		author: "Diệp Lạc Vô Tâm",
		genre: "Ngôn tình",
		year: "2018",
		quantity: 1000,
		image: "/anh/sach/ngontinh/thuong/sach8.jpg",
	},
	{
		title: "Frankenstein",
		author: "Mary Shelley",
		genre: "Kinh dị",
		year: "1818",
		quantity: 1000,
		image: "/anh/sach/kinhdi/top/sach1.jpg",
	},
	{
		title: "Dracula",
		author: "Bram Stoker",
		genre: "Kinh dị",
		year: "1897",
		quantity: 1000,
		image: "/anh/sach/kinhdi/top/sach2.jpg",
	},
	{
		title: "Interview with the Vampire",
		author: "Anne Rice",
		genre: "Kinh dị",
		year: "1976",
		quantity: 1000,
		image: "/anh/sach/kinhdi/top/sach3.jpg",
	},
	{
		title: "The Exorcist",
		author: "William Peter Blatty",
		genre: "Kinh dị",
		year: "1971",
		quantity: 1000,
		image: "/anh/sach/kinhdi/top/sach4.jpg",
	},
	{
		title: "It",
		author: "Stephen King",
		genre: "Kinh dị",
		year: "1986",
		quantity: 1000,
		image: "/anh/sach/kinhdi/top/sach5.jpg",
	},
	{
		title: "The Silence of the Lambs",
		author: "Thomas Harris",
		genre: "Kinh dị",
		year: "1988",
		quantity: 1000,
		image: "/anh/sach/kinhdi/most/sach1.jpg",
	},
	{
		title: "Pet Sematary",
		author: "Stephen King",
		genre: "Kinh dị",
		year: "1983",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach1.jpg",
	},
	{
		title: "The Haunting of Hill House",
		author: "Shirley Jackson",
		genre: "Kinh dị",
		year: "1959",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach2.jpg",
	},
	{
		title: "Bird Box",
		author: "Josh Malerman",
		genre: "Kinh dị",
		year: "2014",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach3.jpg",
	},
	{
		title: "House of Leaves",
		author: "Mark Z. Danielewski",
		genre: "Kinh dị",
		year: "2000",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach4.jpg",
	},
	{
		title: "Tết ở làng Địa Ngục",
		author: "Thảo Trang",
		genre: "Kinh dị",
		year: "2022",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach5.jpg",
	},
	{
		title: "Lý triều dị truyện",
		author: "Phan Cuồng",
		genre: "Kinh dị",
		year: "2017",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach6.jpg",
	},
	{
		title: "Cầu thang gào thét",
		author: "Jonathan Stroud",
		genre: "Kinh dị",
		year: "2013",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach7.jpg",
	},
	{
		title: "Ngôi làng cổ mộ",
		author: "Nguyễn Thục Linh",
		genre: "Kinh dị",
		year: "2020",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach8.jpg",
	},
	{
		title: "Đại Nam dị truyện",
		author: "Phan Cuồng",
		genre: "Kinh dị",
		year: "2016",
		quantity: 1000,
		image: "/anh/sach/kinhdi/thuong/sach9.jpg",
	},
	{
		title: "Dune",
		author: "Frank Herbert",
		genre: "Khoa học viễn tưởng",
		year: "1965",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/top/sach1.jpg",
	},
	{
		title: "Ender's Game",
		author: "Orson Scott Card",
		genre: "Khoa học viễn tưởng",
		year: "1985",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/top/sach2.jpg",
	},
	{
		title: "Foundation",
		author: "Isaac Asimov",
		genre: "Khoa học viễn tưởng",
		year: "1951",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/top/sach3.jpg",
	},
	{
		title: "The Hunger Games",
		author: "Suzanne Collins",
		genre: "Khoa học viễn tưởng",
		year: "2008",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/top/sach4.jpg",
	},
	{
		title: "1984",
		author: "George Orwell",
		genre: "Khoa học viễn tưởng",
		year: "1949",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/top/sach5.jpg",
	},
	{
		title: "Brave New World",
		author: "Aldous Huxley",
		genre: "Khoa học viễn tưởng",
		year: "1932",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/most/sach1.jpg",
	},
	{
		title: "The Martian",
		author: "Andy Weir",
		genre: "Khoa học viễn tưởng",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/most/sach2.jpg",
	},
	{
		title: "Neuromancer",
		author: "William Gibson",
		genre: "Khoa học viễn tưởng",
		year: "1984",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach1.jpg",
	},
	{
		title: "Snow Crash",
		author: "Neal Stephenson",
		genre: "Khoa học viễn tưởng",
		year: "1992",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach2.jpg",
	},
	{
		title: "Ready Player One",
		author: "Ernest Cline",
		genre: "Khoa học viễn tưởng",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach3.jpg",
	},
	{
		title: "Tam Thể",
		author: "Lưu Từ Hân",
		genre: "Khoa học viễn tưởng",
		year: "2006",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach4.jpg",
	},
	{
		title: "Cỗ máy thời gian",
		author: "H. G. Wells",
		genre: "Khoa học viễn tưởng",
		year: "1895",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach5.jpg",
	},
	{
		title: "Người về từ sao Hỏa",
		author: "Andy Weir",
		genre: "Khoa học viễn tưởng",
		year: "2011",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach6.jpg",
	},
	{
		title: "Do Androids Dream of Electric Sheep",
		author: "Philip K. Dick",
		genre: "Khoa học viễn tưởng",
		year: "1968",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach7.jpg",
	},
	{
		title: "Cuộc xâm lược",
		author: "Katherine Applegate",
		genre: "Khoa học viễn tưởng",
		year: "1996",
		quantity: 1000,
		image: "/anh/sach/khoahocvientuong/thuong/sach8.jpg",
	},
	{
		title: "The Little Prince",
		author: "Antoine de Saint-Exupéry",
		genre: "Ngụ ngôn triết lý",
		year: "1943",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/top/sach1.jpg",
	},
	{
		title: "The Alchemist",
		author: "Paulo Coelho",
		genre: "Ngụ ngôn triết lý",
		year: "1988",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/top/sach2.jpg",
	},
	{
		title: "Animal Farm",
		author: "George Orwell",
		genre: "Ngụ ngôn triết lý",
		year: "1945",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/top/sach3.jpg",
	},
	{
		title: "Tuesdays with Morrie",
		author: "Mitch Albom",
		genre: "Ngụ ngôn triết lý",
		year: "1997",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/top/sach4.jpg",
	},
	{
		title: "Jonathan Livingston Seagull",
		author: "Richard Bach",
		genre: "Ngụ ngôn triết lý",
		year: "1970",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/top/sach5.jpg",
	},
	{
		title: "Life of Pi",
		author: "Yann Martel",
		genre: "Ngụ ngôn triết lý",
		year: "2001",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/most/sach1.jpg",
	},
	{
		title: "The Prophet",
		author: "Kahlil Gibran",
		genre: "Ngụ ngôn triết lý",
		year: "1923",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach1.jpg",
	},
	{
		title: "The Giving Tree",
		author: "Shel Silverstein",
		genre: "Ngụ ngôn triết lý",
		year: "1964",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach2.jpg",
	},
	{
		title: "Zen and the Art of Motorcycle Maintenance",
		author: "Robert M. Pirsig",
		genre: "Ngụ ngôn triết lý",
		year: "1974",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach3.jpg",
	},
	{
		title: "Siddhartha",
		author: "Hermann Hesse",
		genre: "Ngụ ngôn triết lý",
		year: "1922",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach4.jpg",
	},
	{
		title: "Người đua diều",
		author: "Khaled Hosseini",
		genre: "Ngụ ngôn triết lý",
		year: "2003",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach5.jpg",
	},
	{
		title: "Tên của đóa hồng",
		author: "Umberto Eco",
		genre: "Ngụ ngôn triết lý",
		year: "1980",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach6.jpg",
	},
	{
		title: "451 độ F",
		author: "Ray Bradbury",
		genre: "Ngụ ngôn triết lý",
		year: "1953",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach7.jpg",
	},
	{
		title: "Suối nguồn",
		author: "Ayn Rand",
		genre: "Ngụ ngôn triết lý",
		year: "1943",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach8.jpg",
	},
	{
		title: "Infinite Jest",
		author: "David Foster Wallace",
		genre: "Ngụ ngôn triết lý",
		year: "1996",
		quantity: 1000,
		image: "/anh/sach/ngungontrietly/thuong/sach9.jpg",
	},
	{
		title: "Harry Potter and the Philosopher's Stone",
		author: "J.K. Rowling",
		genre: "Giả tưởng kỳ ảo",
		year: "1997",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/top/sach1.jpg",
	},
	{
		title: "The Fellowship of the Ring",
		author: "J.R.R. Tolkien",
		genre: "Giả tưởng kỳ ảo",
		year: "1954",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/top/sach2.jpg",
	},
	{
		title: "The Hobbit",
		author: "J.R.R. Tolkien",
		genre: "Giả tưởng kỳ ảo",
		year: "1937",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/top/sach3.jpg",
	},
	{
		title: "A Game of Thrones",
		author: "George R.R. Martin",
		genre: "Giả tưởng kỳ ảo",
		year: "1996",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/top/sach4.jpg",
	},
	{
		title: "The Chronicles of Narnia",
		author: "C.S. Lewis",
		genre: "Giả tưởng kỳ ảo",
		year: "1950",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/top/sach5.jpg",
	},
	{
		title: "Eragon",
		author: "Christopher Paolini",
		genre: "Giả tưởng kỳ ảo",
		year: "2002",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach1.jpg",
	},
	{
		title: "Mistborn",
		author: "Brandon Sanderson",
		genre: "Giả tưởng kỳ ảo",
		year: "2006",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach2.jpg",
	},
	{
		title: "The Wheel of Time",
		author: "Robert Jordan",
		genre: "Giả tưởng kỳ ảo",
		year: "1990",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach3.jpg",
	},
	{
		title: "A Wizard of Earthsea",
		author: "Ursula K. Le Guin",
		genre: "Giả tưởng kỳ ảo",
		year: "1968",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach4.jpg",
	},
	{
		title: "The Name of the Wind",
		author: "Patrick Rothfuss",
		genre: "Giả tưởng kỳ ảo",
		year: "2007",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach5.jpg",
	},
	{
		title: "The Way of Kings",
		author: "Brandon Sanderson",
		genre: "Giả tưởng kỳ ảo",
		year: "2010",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach6.jpg",
	},
	{
		title: "Magnus Chase",
		author: "Rick Riordan",
		genre: "Giả tưởng kỳ ảo",
		year: "2015",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach7.jpg",
	},
	{
		title: "The Trials of Apollo",
		author: "Rick Riordan",
		genre: "Giả tưởng kỳ ảo",
		year: "2016",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach8.jpg",
	},
	{
		title: "The Colour of Magic",
		author: "Terry Pratchett",
		genre: "Giả tưởng kỳ ảo",
		year: "1983",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach9.jpg",
	},
	{
		title: "The Gunslinger",
		author: "Stephen King",
		genre: "Giả tưởng kỳ ảo",
		year: "1982",
		quantity: 1000,
		image: "/anh/sach/giatuongkyao/thuong/sach10.jpg",
	},
];
